### ISSUE TITLE
Acronyme CIGALE à modifier + logo ORECA

### ISSUE THREAD

**Issue by gaelleluneau** [airpaca/CIGALE#51]
Consultation d'inventaires géolocalisés Air Climat Energie
Ajouter le logo ORECA en page d'accueil 
X:\LOGOTHEQUE\LOGOS_EXTERNES\AUTRES_ORGANISMES\ORECA\Logo ORECA 2014\Logo ORECA.jpg

**Comment by rhum1s** [comment]
Ok pour le titre 4861d09eeff20c0118b9889c6228b2db9cd2eeff

**Comment by rhum1s** [comment]
Ok pour logo ORECA 
4e5321dacf6b269bc48c0f0cec7f43676835f7af
