### ISSUE TITLE
[visualisation] infos bulle sur le graphique evolution pluriannuelle

### ISSUE THREAD

**Issue by gaelleluneau** [airpaca/CIGALE#61]
L'info bulle indique NO2 au lieu de NOx. Pour les autres polluants, l'info bulle reste à NO2...

**Comment by gaelleluneau** [comment]
Sur le graphique EPCI/Région, l'info bulle indique "label à définir". Il faudra remettre le nom du polluant concerné.

**Comment by rhum1s** [comment]
Ok, modifiée mais pour l'instant impossible d'inscrire le nb de molécules en indice dans le tooltip.
bd288d384efe13efb017970ec6ac349f00518f0f
