### ISSUE TITLE
[visualisation] partie GES

### ISSUE THREAD

**Issue by gaelleluneau** [airpaca/CIGALE#62]
Ne pas mettre de 's' à gaz à effet de serre
Ecrire les polluants avec les chiffres en indices
Préciser l'unité du PRG (pas d'unité dans la légende de la carte)

**Comment by rhum1s** [comment]
Ok pour les deux premières

**Comment by rhum1s** [comment]
Pour moi, un PRG n'a pas d'unité? on parle de PRG 100 pour 100 ans.
