### ISSUE TITLE
Pb visualisation d'une commune

### ISSUE THREAD

**Issue by gaelleluneau** [airpaca/CIGALE#72]
cf. CC vallée de l'ubaye - serre ponçon. Il y a une commune qu'on ne voit pas...? A voir si ce n'est pas un pb de commune fusionnée ? Je regarderais demain...?

**Comment by rhum1s** [comment]
En fait la commune 4198 a fusionnée avec la 4033 en 2017
Il faut donc mettre à jour la géométrie de ces communes 
Il faut donc sommer les valeurs dans les tables CIGALE pour ces deux communes

- [ ] Faire l'inventaire des communes fusionnées en 2017 et vérifier que l'on ait bien la bonne géométrie.
